// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UWC_API.Data;

#nullable disable

namespace UWCAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UWC_API.Collector", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employeeId"));

                    b.Property<string>("job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("vehicleId")
                        .HasColumnType("integer");

                    b.Property<string>("vehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("employeeId");

                    b.ToTable("Collector");
                });

            modelBuilder.Entity("UWC_API.Janitor", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employeeId"));

                    b.Property<string>("job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("mcpId")
                        .HasColumnType("integer");

                    b.Property<string>("mcpName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("vehicleId")
                        .HasColumnType("integer");

                    b.Property<string>("vehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("employeeId");

                    b.ToTable("Janitor");
                });

            modelBuilder.Entity("UWC_API.MCP", b =>
                {
                    b.Property<int>("mcpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("mcpId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<int>("collectorId")
                        .HasColumnType("integer");

                    b.Property<string>("collectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("janitorId")
                        .HasColumnType("integer");

                    b.Property<string>("janitorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mcpName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<string>("trollerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("mcpId");

                    b.ToTable("MCP");
                });

            modelBuilder.Entity("UWC_API.Vehicle", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("vehicleId"));

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<string>("collectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mcpName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plateNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("vehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("vehicleId");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
